### ISSUE TITLE
Following linux installation steps fails due to obvious issues

### ISSUE THREAD

**Issue by ferasdour** [4anonz/KeyScan#1]
LICENSE  README.md  keyscan  main.cpp  screenshots  server
┌─[root@li210-178]─[/KeyScan]
└──╼ #g++ main.cpp -o keyscan
/usr/bin/ld: cannot open output file keyscan: Is a directory
collect2: error: ld returned 1 exit status

suggested edit to instructions:
g++ main.cpp -o keyscan.bin

**Comment by 4anonz** [comment]
Sorry for the late reply..
Please use
```
g++ main.cpp -o keyscn 
./keysyn
```
