### ISSUE TITLE
No more claims

### ISSUE THREAD

**Issue by ferasdour** [4anonz/KeyScan#2]
"can bypass any antivirus including windows 10 and windows 11 defender" 
"invisible"

heuristics alone makes this relatively highly detected, you can get less detected by obfuscating an msf payload.

Specifically Microsoft detects this on virus total, nothing in the code evades detection. At all. 

There is nothing in the programming of this to make it "fud", deviant generated every run, or anything that would give any relevance to the evading antivirus or "invisible" claim. On windows this program still runs like any other program, does not prevent it from showing in the task manager or netstat (look up 20 yr old rootkits for these techniques). 

Please stop putting false claims in your products.

**Comment by 4anonz** [comment]
You're right. The program runs just like every other programs and I know it isn't invisible to task manager but it still those it's job. Thank you anyways.. I have updated the README. Thank you. I really appreciate it😌.
It was never my intention to do that. I just did without even thinking that this is also a regular program. Thanks again 💖💞
